k3s_server_install = <<-SHELL
    sudo apt-get update
    sudo apt-get install curl
    sudo bash /home/vagrant/install.sh
    SHELL

Vagrant.configure("2") do |config|

    config.vm.box = "debian/bullseye64"

    # Server
    config.vm.define "banthonyTMPbonus" do |server|
        server.vm.hostname = "banthonyTMPbonus"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--name", "banthonyTMPbonus"]
            vb.customize ["modifyvm", :id, "--cpus", "4"]
            vb.customize ["modifyvm", :id, "--memory", "2048"]
        end
        server.vm.provision "shell", inline: k3s_server_install
    end
    config.vm.provision "file", source: "./scripts/install.sh", destination: "/home/vagrant/install.sh"
end